translate-toolkit requires setuptools
otherwise the scripts return error like:
ModuleNotFoundError: No module named 'pkg_resources'

po2ts uses this line:
"from pkg_resources import load_entry_point"